### ISSUE TITLE
xonsh completion

### ISSUE THREAD

**Issue by zasdfgbnm** [zasdfgbnm/tcg#50]

**Comment by anki-code** [comment]
Hi! Thank you for xonsh support!
Please add `xontrib` topic to the repository About settings.
Also you can find useful [xontrib promotion notes](https://github.com/xonsh/xontrib-cookiecutter/tree/master/xontrib-%7B%7Bcookiecutter.project_slug%7D%7D#xontrib-promotion-read-and-remove-this-section).

**Comment by zasdfgbnm** [comment]
@anki-code I have added something to the README.md in https://github.com/zasdfgbnm/tcg/pull/81
